### ISSUE TITLE
Super User: Improvement and Suggestion 

### ISSUE THREAD

**Issue by adityatandon007** [duckduckgo/zeroclickinfo-longtail#103]
**Issue:**   
This IA is working fine, in fact I would say it is working pretty **awesome** but I don't know whether this IA  has the capability of displaying the image or not, so the answers which have image embedded doesn't seem to display properly (image not showing up). For example I searched for **what is rootfs** and it displays the below result

**Screenshot:**

![screenshot from 2017-03-01 17-40-37](https://cloud.githubusercontent.com/assets/25108385/23459692/83575848-fea7-11e6-95c0-6b8baf2f25e7.png)

People to notify
@moollaza @pjhampton 

------
IA Page:  http://duck.co/ia/view/super_user 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @duckduckgo

**Comment by adityatandon007** [comment]
@moollaza do you think it is good to display broken images like the above in our IA

**Comment by moollaza** [comment]
@adityatandon007 thanks for reporting. This is an issue with our image redirect endpoint. The underlying image works, but our proxy doesn't seem to be working for that image.

**Comment by zachthompson** [comment]
![rootfs](https://user-images.githubusercontent.com/1467466/27046982-af45e46c-4f63-11e7-8132-e6485c267a5c.jpg)
