### ISSUE TITLE
Lyrics: Small design bug + malformed hyperlink

### ISSUE THREAD

**Issue by MrChrisW** [duckduckgo/zeroclickinfo-longtail#11]
The Lyrics IA squashes the artist and song name together on a mobile view/under 615px width 

![selection_019](https://cloud.githubusercontent.com/assets/5282264/5516864/e90b974e-88f2-11e4-8545-3c19ab758676.png)
![selection_020](https://cloud.githubusercontent.com/assets/5282264/5516869/19662de6-88f3-11e4-9322-be84db091ae7.png)

Going smaller the artist is correctly aligned underneath the song.
![selection_017](https://cloud.githubusercontent.com/assets/5282264/5516866/04d13fa6-88f3-11e4-934b-a973fd3855e0.png)

**There's also an issue with a malformed song hyperlink - this applies to all lyrics**
![selection_015](https://cloud.githubusercontent.com/assets/5282264/5516874/41cf4542-88f3-11e4-9cee-629b5bb964c6.png)

**Comment by jdorweiler** [comment]
@MrChrisW thanks for catching that.  The link will be fixed too with the next update.

**Comment by MrChrisW** [comment]
@jdorweiler Great, thanks for the update! I'll close this issue now.
