### ISSUE TITLE
Ask Ubuntu: show the release date of the answer given

### ISSUE THREAD

**Issue by MOTSM** [duckduckgo/zeroclickinfo-longtail#124]
in my experience especially in the linux world it is abolutely essential to know _when_ the solution/workaround to your problem/issue was released/posted. the IA Ask Ubuntu shows answers very neatly, but to make sure it is what i need, i have to check the site itself, just because i don't know the date from the IA.

------
IA Page:  http://duck.co/ia/view/ask_ubuntu 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @duckduckgo

**Comment by pjhampton** [comment]
Thanks @MOTSM. I have passed your feedback onto the team.
