### ISSUE TITLE
MetroLyrics has autoplay ads with audio and it's really jarring

### ISSUE THREAD

**Issue by viniciusggm** [duckduckgo/zeroclickinfo-longtail#137]
Can't another website be used in it's place?

(Thanks for developing this btw, othewise it'd be great!)

------
IA Page:  http://duck.co/ia/view/lyrics 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jdorweiler

**Comment by revnoah** [comment]
Most of the time, I'm already listening to the song and want to read along with the music. MetroLyrics is an obnoxious resource under those circumstances.

**Comment by nemobis** [comment]
No longer relevant as MetroLyrics closed in June 2021. Please close this issue.
Ref: https://en.wikipedia.org/wiki/Metrolyrics
