### ISSUE TITLE
MetroLyrics: 

### ISSUE THREAD

**Issue by jonnybradley** [duckduckgo/zeroclickinfo-longtail#139]
Made me agree to a load of cookie tracking and data harvest and then said "Unfortunately, we aren't authorized to display these lyrics, Read more: Jimi Hendrix - The Wind Cries Mary Lyrics | MetroLyrics"

There is no more... drop these people as a ddg recommended site please!   
------
IA Page:  http://duck.co/ia/view/lyrics 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jdorweiler

**Comment by nemobis** [comment]
No longer relevant as there is no link to MetroLyrics any more. Please close this issue.

Current example output (in Italian) for the same song mentioned by the docs:
![Screenshot_20210821_180138](https://user-images.githubusercontent.com/901528/130326020-1d714d4f-4564-4ddf-b840-cf3f88e81ede.png)

**Comment by jonnybradley** [comment]
Thanks
