### ISSUE TITLE
The links under "SOURCE" are broken

### ISSUE THREAD

**Issue by iambibhas** [duckduckgo/zeroclickinfo-longtail#16]
Hi,

Seems like the urls to this repo from almost all the instant answers are broken. The sources don't seem to exist here. Any clue where they are and if I can help fix it somehow?

-- http://duck.co/ia/view/super_user

**Comment by moollaza** [comment]
Hi @iambibhas -- thanks for pointing this out! The IA pages are not yet complete, and are still under active development so there's likely some bug lurking around.

I believe right now these links are being generated and in this case the Longtail is actually not an open-source one, so the links obviously don't work.

I'll be sure to let the team know!

//cc @MariagraziaAlastra @jdorweiler

**Comment by iambibhas** [comment]
Hey @moollaza, thanks for the reply. May I know why they are not open source? I was hoping to go through the superuser one and see if it could be extended to show Q/A for more keywords. I assumed they are open source.

**Comment by moollaza** [comment]
@iambibhas I believe the StackExchange Longtail is just a very old, legacy IA that was made before we had open-source Instant Answers. We just haven't had the time to opensource most of the legacy Longtails yet.

For now I think you'll just need to file a bug report and we'll have to fix it ourselves.

**Comment by jdorweiler** [comment]
It's been fixed.  Thanks @iambibhas
