### ISSUE TITLE
IA for INDIA is showing an music album name

### ISSUE THREAD

**Issue by abhijainn27** [duckduckgo/zeroclickinfo-longtail#20]
The IA for India shows an answer for an album named INDIA instead f the country INDIA which is on the top of the wikipedia search.

**Comment by MariagraziaAlastra** [comment]
Thanks!

**Comment by moollaza** [comment]
@abhijainn27 I'm not quite sure what IA you're referring to -- can you please provide a link?

When I search "india" I get the Wikipedia Fathead result for the country

**Comment by abhijainn27** [comment]
It has been changed now. Earlier the IA was showing an album of some Band for the IA India.

**Comment by MariagraziaAlastra** [comment]
Yeah that's true, on Sunday I saw that too. Well, I guess it's solved now, good!

Thank you @abhijainn27 for pointing out the issue, closing since it's fixed :)
