### ISSUE TITLE
MetroLyrics: full lyrics in 'zeroclick box'

### ISSUE THREAD

**Issue by kcpr** [duckduckgo/zeroclickinfo-longtail#22]
Hello,
Would adding option to show full lyrics in 'zeroclick box' be a problem? I know they are sometimes long, but it shouldn't be so horrible for user and even adding some scrollbar doesn't seem like a big deal.
That would be really helpful.
Thanks in advance and for all that's already done.

------
IA Page:  http://duck.co/ia/view/lyrics

**Comment by jdorweiler** [comment]
@kcpr Thanks for the suggestion!  That would be great but unfortunately I think we would need to pay for some license to do that.

**Comment by kcpr** [comment]
That's sad. I had a thought like that, but decided to ask anyway. I assume that You asked them about that or got some reliable source of this information.
Thanks anyway.

**Comment by jdorweiler** [comment]
@kcpr yeah it came up when I was developing the IA.
