### ISSUE TITLE
Programmers StackExchange: Empty div creating poor vertical centering of content

### ISSUE THREAD

**Issue by chrismorast** [duckduckgo/zeroclickinfo-longtail#23]
Looks like there's an empty div with the class "c-base__links" below the "c-info__links" div that off-centering the content vertically.

![screen shot 2015-08-19 at 7 48 04 am](https://cloud.githubusercontent.com/assets/7061920/9359595/c4e9077c-4646-11e5-8830-702d31091f23.png)

This may be an issue on all StackExchange IAs. Can we remove these?

![screen shot 2015-08-19 at 7 44 20 am](https://cloud.githubusercontent.com/assets/7061920/9359605/d03b3fbe-4646-11e5-885b-eeaae8a5b7e9.png)

cc @moollaza 
@abeyang , can you make sure that if this is part of the template we have it completely removed (unless of course it's necessary)?

------
IA Page:  http://duck.co/ia/view/programming_longtail

**Comment by moollaza** [comment]
Looks like this is fixed? https://duckduckgo.com/?q=which+hashing+algorithm+is+best+for+uniqueness+and+speed&t=ffab&ia=qa

**Comment by tagawa** [comment]
Yes, I think we can close this. There's no `c-base__links` class - only one `c-base`, used in a div wrapping the IA.
