### ISSUE TITLE
MetroLyrics: Bob Dylan song not showing

### ISSUE THREAD

**Issue by zekiel** [duckduckgo/zeroclickinfo-longtail#27]
Lyrics are:
"don't need a weatherman to know which way the wind blows"
which is from Subterranean Homesick Blues

Query:
https://duckduckgo.com/?q=don%27t+need+a+weatherman+to+know+which+way+the+wind+blows

---

IA Page:  http://duck.co/ia/view/lyrics

**Comment by pjhampton** [comment]
Hey @zekiel 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
