### ISSUE TITLE
MetroLyrics: Nop result for: "things aren't cooking in my kitchen lyrics"

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-longtail#28]
Posted on Twitter: https://twitter.com/tomhannen/status/625052876176556032

---

IA Page:  http://duck.co/ia/view/lyrics

**Comment by uderani** [comment]
Seems to be working correctly now. Can be closed!
![screenshot-2018-6-7 things ain t cooking in my kitchen lyrics at duckduckgo](https://user-images.githubusercontent.com/7395076/41099962-ab1ff0f4-6a7d-11e8-9ce7-7291c79b8564.png)
