### ISSUE TITLE
MetroLyrics: Apostrophes are removed when displaying in DDG

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-longtail#40]
This also affects capitalisation, for example the name "Gilbert O'Sullivan" becomes "Gilbert Osullivan"
Example: https://duckduckgo.com/?q=alone%20again%20naturally

I haven't checked but this may affect other characters as well, e.g. hyphens.

---

IA Page:  http://duck.co/ia/view/lyrics

**Comment by pjhampton** [comment]
I believe there to be extensive work to this IA in the future. Closing for now.
