### ISSUE TITLE
Ask Ubuntu: Markdown not completely supported

### ISSUE THREAD

**Issue by mananaBanana** [duckduckgo/zeroclickinfo-longtail#41]
Comments on AskUbuntu with Markdown tags (such as `<b> </b>`) are shown along with the tag instead of being parsed and rendered appropriately.
[Example Query](https://duckduckgo.com/?q=commandline+view+all+installed+programs+ubuntu&ia=qa)

------
IA Page:  http://duck.co/ia/view/ask_ubuntu

**Comment by zachthompson** [comment]
@mananaBanana Thanks for raising this.  Should be fixed.
