### ISSUE TITLE
MetroLyrics: IA shows a fraction of the lyrics

### ISSUE THREAD

**Issue by EpicWolverine** [duckduckgo/zeroclickinfo-longtail#42]
I love the lyrics IA, but it's incredibly frustrating when I have to click on the "More at MetroLyrics" button to see the entire song. Why is the whole song not displayed when "+ Show More" is clicked? Would doing so violate DDG's agreement with MetroLyrics or is it simply an old design decision that needs to be fixed?

------
IA Page:  http://duck.co/ia/view/lyrics

**Comment by jdorweiler** [comment]
@EpicWolverine we can't show the full song lyrics.  We might be able to at least show the box expanded so you don't need to click the (+) show more to see one or two additional lines.

**Comment by bsstoner** [comment]
The issue with expanding by default is that the amount of data we can show is wildly inconsistent from one song to the next. If we expanded by default there would be a lot of cases where the height of the IA would be way to big.

There's some other options we could explore:
1) Just chop off the text, and redirect the show more to metrolyrics?
2) Explore other UI's, like horizontally chunking up the lyrics?
3) Play with a more dynamic threshold for the expand logic?

**Comment by jdorweiler** [comment]
I could generate a distribution of the length of the lyrics.  My guess is that a majority will fall between 5-10 lines long.

**Comment by jdorweiler** [comment]
Looks like increasing the height 7-8 lines would cover the majority of results. 
![selection_087](https://cloud.githubusercontent.com/assets/1882892/14504392/a212125a-0182-11e6-9ba7-c237f80d103b.png)

**Comment by bsstoner** [comment]
Awesome, data!

**Comment by bsstoner** [comment]
@jdorweiler can you create a task in general front-end to make that change?

**Comment by jdorweiler** [comment]
Thanks for the issue @EpicWolverine.  @bbraithwaite and @bsstoner fixed this internally.

**Comment by EpicWolverine** [comment]
You're welcome, and thank you for handling it.
