### ISSUE TITLE
AndroidEnthusiasts: 

### ISSUE THREAD

**Issue by poornagurram** [duckduckgo/zeroclickinfo-longtail#43]
------The Instant Answer is not appearing for the queries given over the instant answer overview page.
![image](https://cloud.githubusercontent.com/assets/9065157/13201484/9d575d5e-d899-11e5-9cb8-06445199deb3.png)
Empty Box is getiing displayed when typed the query 

> android apk sd card

![image](https://cloud.githubusercontent.com/assets/9065157/13201486/b68fd1a2-d899-11e5-8af6-1a6edf939f86.png)

IA Page:  http://duck.co/ia/view/android_enthusiasts

**Comment by jdorweiler** [comment]
Updated the examples.
