### ISSUE TITLE
Fuel Economy: IA doesn't trigger on fuel efficiency

### ISSUE THREAD

**Issue by stevenmg** [duckduckgo/zeroclickinfo-longtail#45]
@zachthompson IA doesn't trigger if I search 2004 toyota prius fuel efficiency. It does trigger if I replace efficiency with economy.

------
IA Page:  http://duck.co/ia/view/fuel_economy

**Comment by zachthompson** [comment]
Thank you!

**Comment by zachthompson** [comment]
@stevenmg Should be fixed in today's release - https://duckduckgo.com/?q=2004+toyota+prius+fuel+efficiency&ia=fueleconomy
