### ISSUE TITLE
AndroidEnthusiasts: 

### ISSUE THREAD

**Issue by OscarMZ** [duckduckgo/zeroclickinfo-longtail#46]
Some example queries don't work (I don't know if only to me), like:

https://duckduckgo.com/?q=android%20apk%20sd%20card&ia=qa 
https://duckduckgo.com/?q=how+to+root+my+android+device

------
IA Page:  http://duck.co/ia/view/android_enthusiasts

**Comment by zekiel** [comment]
Thanks for the heads up @OscarMZ  -- and for updating the Programming IA coverage table :)

**Comment by jdorweiler** [comment]
Updated the examples.
