### ISSUE TITLE
Stack Exchange: Displays wrong SE question on input 'traceroute names'

### ISSUE THREAD

**Issue by jsenn** [duckduckgo/zeroclickinfo-longtail#47]
A search for [traceroute names](https://duckduckgo.com/?q=traceroute+names) displays an instant answer with the correct title from a Unix SE question, but the body of an incorrect Tex SE question.

Interestingly, the ID of the correct Unix SE question is 21612, while the ID of the displayed Tex SE question is 21614.

------
IA Page:  http://duck.co/ia/view/stack_overflow 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @duckduckgo

**Comment by jdorweiler** [comment]
@jsenn it's been fixed, thanks for reporting.
