### ISSUE TITLE
MetroLyrics: broken link on IA-Page

### ISSUE THREAD

**Issue by fzzr-** [duckduckgo/zeroclickinfo-longtail#53]
>Back-End Files
>[Lyrics.pm](https://github.com/duckduckgo/zeroclickinfo-longtail/tree/master/lib/DDG/Longtail/Lyrics.pm)

------
IA Page:  http://duck.co/ia/view/lyrics 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jdorweiler

**Comment by jdorweiler** [comment]
fixed
