### ISSUE TITLE
Arqade: h1 heading elements fill the entire IA

### ISSUE THREAD

**Issue by angussidney** [duckduckgo/zeroclickinfo-longtail#54]
If the first line of an answer from [Arqade](http://gaming.stackexchange.com/) is a `<h1>` element (`#` in markdown), it will fill the entire IA box on DuckDuckGo, leaving no space for the actual answer.

Example search: [steam how to stop updates](https://duckduckgo.com/?q=steam+how+to+stop+updates)

![duckduckgo bug h1](https://cloud.githubusercontent.com/assets/4848802/14417923/bc9f2f94-fffd-11e5-8685-6eb20082447e.PNG)

Also, if the heading is longer than approximately 30 characters, all further characters will be chopped off.

A potential fix would be to make h1 headings smaller, display some of the text below them, or remove the heading entirely.

---

IA page: https://duck.co/ia/view/arqade
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @duckduckgo

**Comment by moollaza** [comment]
This has been fixed.
