### ISSUE TITLE
AndroidEnthusiasts: Should trigger more

### ISSUE THREAD

**Issue by edgesince84** [duckduckgo/zeroclickinfo-longtail#56]
There should be more triggers to find related Q/A threads for this IA.  Searching "increase battery life android" doesn't trigger the example query "What can I do to increase battery life on my Android device."

Searching "Nexus 6P wrong time," an answered thread of the front page of the Android Enthusiasts page, doesn't show any IA.

------
IA Page:  http://duck.co/ia/view/android_enthusiasts 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @duckduckgo

**Comment by zachthompson** [comment]
In your first example, there's not much we can do about atm (or easily.)  The Stack Exchange result is pushed out of the top 15 by changing the query.

Your second example was too new of a post and wasn't loaded.  [It is now](https://duckduckgo.com/?q=Nexus+6P+wrong+time&t=ffab&ia=qa&iax=1) however.
