### ISSUE TITLE
Unix: No longer triggering

### ISSUE THREAD

**Issue by edgesince84** [duckduckgo/zeroclickinfo-longtail#58]
This doesn't seem to be triggering any longer.  None of the example queries from the IA page are triggering the IA.

------
IA Page:  http://duck.co/ia/view/unix 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @duckduckgo

**Comment by zachthompson** [comment]
It's triggering.  Example queries updated.
