### ISSUE TITLE
Test issue, please ignore

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-longtail#59]
> used for back-end tests within the Community Platform repo. 

//cc @jbarrett

**Comment by zachthompson** [comment]
@MariagraziaAlastra ping, do you need this test open still?

**Comment by jbarrett** [comment]
I believe this is used in the unit tests for IA metadata. Only way to properly test Github integration, really.

**Comment by GuiltyDolphin** [comment]
@jbarrett :cry:

Would it not be possible to re-use the same test issue? The triggering should happen on new issues + changes, shouldn't it?

**Comment by jbarrett** [comment]
I don't understand the question. We are reusing the same test issue - this one.

**Comment by MariagraziaAlastra** [comment]
@zachthompson @GuiltyDolphin  as @jbarrett said, this is used for back-end tests within the Community Platform repo. 

See the code [here](https://github.com/duckduckgo/community-platform/blob/master/t/github.t#L30-L41).

**Comment by GuiltyDolphin** [comment]
@jbarrett Sorry, I just meant for testing pull requests that detect changes in issues, re-using the same issue by changing it and then opening/closing it (over multiple PRs).

@MariagraziaAlastra Ah, okay! I was thinking along the lines of https://github.com/duckduckgo/community-platform/pull/1397 (manual test).

 So, the test *will* re-use this issue? And change it to check for the correct response? :+1:

**Comment by moollaza** [comment]
@MariagraziaAlastra @jbarrett does this still need to be open?
