### ISSUE TITLE
StackOverflow IA example queries not working

### ISSUE THREAD

**Issue by gaulrobe** [duckduckgo/zeroclickinfo-longtail#62]
The first two example queries on https://duck.co/ia/view/stack_overflow are not triggering the StackOverflow IA. Not entirely sure how the IA works, but there may be a problem with triggering, or maybe the data that used to be returned upon triggering is no longer there. @moollaza thoughts?

**Comment by zachthompson** [comment]
Thanks for pointing this out.  Fixed.
