### ISSUE TITLE
MetroLyrics: show full lyrics on results

### ISSUE THREAD

**Issue by NaveenKarippai** [duckduckgo/zeroclickinfo-longtail#63]
Currently, the result shows only first few lines of the lyrics. We could change the IA to show the **full lyrics (all lines)** on results?

------
IA Page:  http://duck.co/ia/view/lyrics 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jdorweiler

**Comment by jdorweiler** [comment]
@NaveenKarippai Great idea but we would have to pay licensing fees for each song :astonished:
