### ISSUE TITLE
Science Fiction and Fantasy: IA not triggered 

### ISSUE THREAD

**Issue by NaveenKarippai** [duckduckgo/zeroclickinfo-longtail#65]
The sample queries provided on IA page ([origin of star wars](https://duckduckgo.com/?q=origin+of+star+wars&ia=web))  does not trigger the IA.

------
IA Page:  http://duck.co/ia/view/science_fiction 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @duckduckgo

**Comment by zekiel** [comment]
Thx for catching this @NaveenKarippai  Not sure why they're failing but we'll take a look!

**Comment by zachthompson** [comment]
Thank you, fixed.
