### ISSUE TITLE
Seasoned Advice: not triggered for sample queries

### ISSUE THREAD

**Issue by NaveenKarippai** [duckduckgo/zeroclickinfo-longtail#66]
The IA is not triggered for sample queries such as [how to chop onions without crying](https://duckduckgo.com/?q=how+to+chop+onions+without+crying&atb=v9&ia=recipes).   

------
IA Page:  http://duck.co/ia/view/seasoned_advice 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @duckduckgo

**Comment by zekiel** [comment]
thx for the heads up!

**Comment by zachthompson** [comment]
Updated.
