### ISSUE TITLE
MetroLyrics: Wrong result

### ISSUE THREAD

**Issue by xrisk** [duckduckgo/zeroclickinfo-longtail#73]
Searching for "On the plane blackfield" brings up lyrics for a Ed Sheeran song.

---

IA Page:  http://duck.co/ia/view/lyrics 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jdorweiler

**Comment by gautamkrishnar** [comment]
@pjhampton here

**Comment by pjhampton** [comment]
What is this @gautamkrishnar? Spam?

**Comment by pjhampton** [comment]
Sorry @xrisk. I thought I was commenting on another issue!! Sorry again!

💙  💛

**Comment by gautamkrishnar** [comment]
@pjhampton sorry for the confusion. Since it used wrong format for tittle i thought that it was spam...

**Comment by gautamkrishnar** [comment]
@xrisk while giving tittle for issue, please remember to follow the guideline. For this issue you must give this as a tittle:
lyrics: add On the plane blackfield lyrics

Please try to use **IA-name: issue-tittle** for the tittle while opening new issues
