### ISSUE TITLE
Русский язык (Russian Language StackExchange): 

### ISSUE THREAD

**Issue by wellkun** [duckduckgo/zeroclickinfo-longtail#90]
------
IA Page:  http://duck.co/ia/view/rus_stackexchange 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @ddg

**Comment by gautamkrishnar** [comment]
@GuiltyDolphin spam

**Comment by pjhampton** [comment]
Hey @wellkun,

I'm going to close this. I'm not sure what happened. If you need any help hit me up on our Slack channel: https://quackslack.herokuapp.com/ - @pjhampton
