### ISSUE TITLE
Strange IA when searching "GCD 0"

### ISSUE THREAD

**Issue by kumarankit0411** [duckduckgo/zeroclickinfo-longtail#91]
I was just testing GCD calculation and then saw a strange IA on this search term "0 gcd". I don't know if I am right but the longtail generated on this search term doesn't seem fit for this query.

**Comment by gautamkrishnar** [comment]
I cant find a GCD IA. 
https://duck.co/ia?q=greatest

**Comment by GuiltyDolphin** [comment]
@gautamkrishnar We have the [GreatestCommonFactor](https://duck.co/ia/view/greatest_common_factor) Goodie.

**Comment by gautamkrishnar** [comment]
Yes got it... 
https://duckduckgo.com/?q=GCD+0&t=h_&ia=qa
Its a bug. Thanks for finding 👍

**Comment by GuiltyDolphin** [comment]
@kumarankit0411 @gautamkrishnar The lack of triggering from GreatestCommonFactor isn't a bug, see https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3167.

**Comment by gautamkrishnar** [comment]
@GuiltyDolphin yes just saw that. I think instead of returning `undef` we must display something like `Cannot compute Greatest common factor` to prevent other IA from triggering for `GCD 0`

**Comment by GuiltyDolphin** [comment]
@gautamkrishnar We do not display 'error' results, we just don't trigger the IA.

This is an issue of overtriggering for the LongTail, not an undertriggering for the Goodie.

**Comment by gautamkrishnar** [comment]
@GuiltyDolphin Thanks for correcting me. Yes we must not display error results... 👍

**Comment by zachthompson** [comment]
This is an edge case that I don't see us addressing any time soon.  All of the links point to the "greatest common divisor of 0".
