### ISSUE TITLE
IA for StackOverflow doesn't show accepted answer (shows highest rated?)

### ISSUE THREAD

**Issue by rltbennett** [duckduckgo/zeroclickinfo-longtail#93]
For the query "python merge dicts" (https://duckduckgo.com/?q=python+merge+dicts&ia=qa) the accepted answer, which is also the correct and best answer, is not shown as the IA. A different answer, which shows lower quality code, is shown instead.

At time of writing, the accepted answer is only voted one point lower than the highest voted answer so the IA may change in the near future.

**Comment by zachthompson** [comment]
For now, the highest rated is the one we go with.  Too many bad answers are prematurely accepted by the OP and never updated.  This will update in the near future and we do have it on our radar to figure out ways to update more frequently.

**Comment by rltbennett** [comment]
Currently, for the same query, the instant answer being shown is neither top rated nor the accepted answer. In general I think the best answer to show is the one closest to the top of the page -- not sure what algorithm SO uses to rank answers, but the first one on the list tends to be the best. In this case, the first answer on the list is "the best" (subjective), the highest rated, and the accepted answer.

**Comment by zachthompson** [comment]
Answers have been updated.
